# e2e_test_data.py

LOCATION = "Tel Aviv"
NUMBER_OF_ADULTS = 2
NUMBER_OF_CHILDREN = 1
PHONE_NUMBER = '050123123'
TIMEOUT = 8000
OFFER_DETAILS_FILE = 'best_offer_data'
VALIDATE_OFFER_DATA_FILE = 'validate_offer_data'